marketplace: "amazon.co.uk"
target_acos: 0.30

bid_steps:
  up_pct: 0.15
  down_pct: 0.10

thresholds:
  min_clicks: 20
  min_conversions: 2
  harvest_cvr: 0.10

negatives_scan:
  include_terms: ["brew","brewing","airlock","ferment","demijohn","bung","grommet","wine","cider","mead","kombucha","heat belt","heat mat","heat pad","fermentation"]
  exclude_terms: ["reptile","terrarium","seed","seedling","plant","pet","dog","cat","car","12v","water tank","aquarium","vivarium","sous vide","coffee","tea pot"]
  price_min: 10
  price_max: 60
  rating_min: 3.8
  reviews_min: 20
  brand_whitelist: []
  brand_blacklist: []

keepa:
  domain_map:
    amazon.co.uk: 2
    amazon.com: 1
    amazon.de: 3
    amazon.fr: 8
    amazon.it: 10
    amazon.es: 9
  prefer_rest: true
  history: 0
  timeout: 25
  retries: 2

  keyword_mining:
  min_df: 2            # 至少出现在多少个竞品上才纳入（去噪）
  max_top: 200         # 关键词榜单最多返回多少条
  ngram_range: [1, 3]  # 1~3 gram
  stopwords: ["for","with","and","the","a","of","to","in","on","set","kit","stainless","steel","304","home","brewing","beer","brewer","brewers","brews"]
  suggest_probe: false # 如需调用搜索建议探针（可后续接三方），先关
  weight:
    title: 1.0
    bullets: 0.7
    aplus: 0.4
    brand_bonus: 0.0   # 不对品牌词加分（避免偏向品牌）
  bsr_correlation_window: 5  # 用于 BSR 同步信号的窗口天数

